# Generated by Django 4.2.4 on 2023-08-31 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.RunSQL([
            "INSERT INTO countries (name, active, created_date, updated_date) VALUES ('Colombia', 1, NOW(), NOW());",
            "INSERT INTO countries (name, active, created_date, updated_date) VALUES ('Estados Unidos', 1, NOW(), NOW());"
        ]),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.country')),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.RunSQL([
            "INSERT INTO states (name, active, created_date, updated_date, country_id) VALUES ('Antioquia', 1, NOW(), NOW(), 1);",
            "INSERT INTO states (name, active, created_date, updated_date, country_id) VALUES ('Cundinamarca', 1, NOW(), NOW(), 1);",
            "INSERT INTO states (name, active, created_date, updated_date, country_id) VALUES ('Bogotá', 1, NOW(), NOW(), 1);",

            "INSERT INTO states (name, active, created_date, updated_date, country_id) VALUES ('Texas', 1, NOW(), NOW(), 2);",
            "INSERT INTO states (name, active, created_date, updated_date, country_id) VALUES ('Florida', 1, NOW(), NOW(), 2);",
            "INSERT INTO states (name, active, created_date, updated_date, country_id) VALUES ('Ohio', 1, NOW(), NOW(), 2);"
        ]),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.state')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.RunSQL([
            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Medellín', 1, NOW(), NOW(), 1);",
            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Puerto berrío', 1, NOW(), NOW(), 1);",
            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Sabaneta', 1, NOW(), NOW(), 1);",

            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Zipaquirá', 1, NOW(), NOW(), 2);",
            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Facatativá', 1, NOW(), NOW(), 2);",
            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Mosquera', 1, NOW(), NOW(), 2);",

            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Bogotá', 1, NOW(), NOW(), 3);",


            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Houston', 1, NOW(), NOW(), 4);",
            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Austin', 1, NOW(), NOW(), 4);",
            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Dallas', 1, NOW(), NOW(), 4);",


            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Miami', 1, NOW(), NOW(), 5);",
            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Orlando', 1, NOW(), NOW(), 5);",
            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Tampa', 1, NOW(), NOW(), 5);",

            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Columbus', 1, NOW(), NOW(), 6);",
            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Cleveland', 1, NOW(), NOW(), 6);",
            "INSERT INTO cities (name, active, created_date, updated_date, state_id) VALUES ('Cincinnati', 1, NOW(), NOW(), 6);"
        ]),
    ]
