# Generated by Django 4.2.4 on 2023-08-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gender_types',
            },
        ),
        migrations.RunSQL([
            "INSERT INTO gender_types (name, active, created_date, updated_date) VALUES ('Hombre', 1, NOW(), NOW());",
            "INSERT INTO gender_types (name, active, created_date, updated_date) VALUES ('Mujer', 1, NOW(), NOW());"
        ]),
    ]
